## Operations on Tensors


In [1]:
import torch
int_16_tensor=torch.tensor([3.2,4.5],dtype=torch.int16)
float_32_tensor=torch.tensor([3.2,4.5],dtype=None)

float_16_tensor=torch.tensor([3.2,4.5],dtype=torch.float16)
int_32_tensor=torch.tensor([3.2,4.5],dtype=torch.int32)


In [2]:
float_16_tensor*float_32_tensor

tensor([10.2375, 20.2500])

In [3]:
int_16_tensor*float_16_tensor

tensor([ 9.5938, 18.0000], dtype=torch.float16)

In [4]:
long_tensor=torch.tensor([3.2,4.5],dtype=torch.long)

long_tensor*float_32_tensor

tensor([ 9.6000, 18.0000])

**NOTE**: Although these are of different types their multiplication doesnt throw an error

### **Indexing in tensors**

In [5]:
tensor=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f"First row:{tensor[0]}")
print(f"First column:{tensor[:,0]}")
print(f"Last column:{tensor[:,-1]}")
print(f"Subtensor:{tensor[0:2,1:3]}")
print(tensor)

First row:tensor([1, 2, 3])
First column:tensor([1, 4, 7])
Last column:tensor([3, 6, 9])
Subtensor:tensor([[2, 3],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### **Contacenating tensors**

In [6]:
tensor_2=torch.tensor([[10,11,12],[13,14,15],[16,17,18]])
torch.cat((tensor,tensor_2),dim=1)

tensor([[ 1,  2,  3, 10, 11, 12],
        [ 4,  5,  6, 13, 14, 15],
        [ 7,  8,  9, 16, 17, 18]])

### **Manipulating tensors**

Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [7]:
## Manipulating a tensor

tensor=torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [8]:
tensor*10

tensor([10, 20, 30])

In [9]:
# Alternate way to multiply
torch.mul(tensor,10)

tensor([10, 20, 30])

In [10]:
tensor/8

tensor([0.1250, 0.2500, 0.3750])

### **Matrix Multiplication**

There are two ways to perform multiplication in NN:
1. Element wise multiplication
2. Matrix multiplication (dot product)


**NOTE:** There are two main rules for matrix multiplication- 

1. The inner dimensions should match
- (3,2) @ (3,2) wont work
- (2,3) @(3,2) will work.

This is illustrated in the cell below as well
2. The resulting matrix should have the shape of the outer dimension
- (2,3) @ (3,2) -> (2,2)

In [11]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4943, 0.5749, 0.3294],
        [0.5883, 0.6947, 0.4135],
        [0.7892, 0.9517, 0.5950]])

Note the result is a 3x3 matrix

In [ ]:
# Element wise multiplication

tensor=torch.tensor([1,2,3])
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication 

torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

Matrix mutliplication by hand

tensor=[1,2,3]

(1 * 1)+(2 * 2)+(3 * 3)=14


In [ ]:
%%time
# matrix mutliplication using a matrix

value=0
for i in range(len(tensor)):
    value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 9.73 ms


In [ ]:
%%time
# the matmul funcition is optimized and faster
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

Shape errors are very common in deep learning

In [ ]:
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])

tensor_B=torch.tensor([[7,10],[8,11],(9,12)])

torch.mm(tensor_A,tensor_B)   # torch.mm is same as toch.matmul as they are used frequently

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix these issues we can manipulate the shape of one of our tensors using transpose

A transpose switches the dimensions of a vector

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
print(tensor_B.shape)
print(tensor_B.T.shape)

torch.Size([3, 2])
torch.Size([2, 3])


In [ ]:
# Matrix multiplication operation will work when the tensor_B is transposed

print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"New shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.T.shape}")

print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}")
print("Output:")

output=torch.mm(tensor_A,tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])
Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


### **Finding the min, max , sum of a tensor**

In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

**NOTE:** When this kind of an error comes up we can quickly go to the pytorch documentation and search up for torch.mean, to find what input type it expects.


In this case we need the datatype to floating point, as mentioned in the error itself as the documentation doesnt provide enough details

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### **Finding positional min and max of a tensor**

Finding the position at which the min and max occur

In [ ]:
x.argmin()


tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x.argmin()

tensor(0)