## Reshaping, Stacking, Squeezing and Unsqueezing tensors

* Reshaping- reshapes an input tensor to a defined shape
* View- return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking- combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze- removes all `1` dimensions from a tensor
* Unsqueeze- add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted(swapped) in a certain way


In [1]:
import torch

x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

### **Reshape Operation**

***torch.reshape(input, shape) -> Tensor***

args:

- input(Tensor): the tensor to be reshaped

- shape(tuple of int): the new shape

Returns a tensor with same data and number of elements as input , but with the specified shape. 

In [2]:
# Add an extra dimension
# The reshape operation should be compatible with the number of elements in the tensor 
x_reshaped=x.reshape(1,7)
x_reshaped,x_reshaped.shape


RuntimeError: shape '[1, 7]' is invalid for input of size 9

We get an error here as we are trying to squeeze 9 elements into 7 which is not possible

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped=x.reshape(2,9)
x_reshaped,x_reshaped.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

This wil also not work as we are trying to reshape 9 elements into 18 elements

In [ ]:
x_reshaped_n=x.reshape(9,1)
x_reshaped_n,x_reshaped_n.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
y=torch.arange(1.,11.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
y_reshaped=y.reshape(2,5)
y_reshaped,y_reshaped.shape


(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

This works because 2x5=10 and the inital shape was also 10

In [ ]:
y=torch.arange(1.,13.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
y_reshaped=y.reshape(3,4)
y_reshaped,y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

### **View Operation** 

***torch.view(***shape****) *-> Tensor***

args:

- shape(torch.Size or int): the desired size

Returns a new tensor with same data as self tensor but a different shape

**NOTE:** Very similar to Reshape operation, only difference is the view shares the same memory as the original tensor

In [ ]:
# Change the view

z=x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

**NOTE:** Changing z changes x (because a view of tensor shares the same memory of the original tensor)

In [ ]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### **Stack  Operation**

***torch.stack(tensors, dim=0,out=None) -> Tensor***

args:

- tensors: sequence of tensors to concaenate

- dim(int,optional): dimension to insert. Default is 0 which inserts along rows 
    
- out(Tensor,optional): the output tensor

Concatenates a sequence of tensors along a new dimension. All tensors need to be of same size

***torch.hstack(tensors,out=None) -> Tensor***
 
- Stack the tensors in sequence horizontally (column wise)

***torch.vstack(tensors,out=None) -> Tensor***

- Stack the tensors in sequence vertically (row wise). Equivalent to stack with dim=0 for 1D tensors

In [ ]:
# Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x,x],dim=0)
x_stacked,x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([5, 9]))

In [ ]:
x_stacked=torch.stack([x,x,x,x,x],dim=1)
x_stacked,x_stacked.shape

(tensor([[5., 5., 5., 5., 5.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8.],
         [9., 9., 9., 9., 9.]]),
 torch.Size([9, 5]))

In [ ]:
x_h_stacked=torch.hstack([x,x,x,x,x])
x_h_stacked,x_h_stacked.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([45]))

hstack is the equivalent of concatenation along the first axis for 1-D tensors

In [ ]:
x_v_stacked=torch.vstack([x,x,x,x,x])
x_v_stacked,x_v_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([5, 9]))

vstack achieves the same result as torch.stack using dim=0 for 1D and higher dimensional tensors

In [ ]:
x_stacked=torch.stack([x,x,x,x,x],dim=2)
x_stacked,x_stacked.shape

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Here if we try to do dim=2 it wont work, as this dim should be between 0 and the number of dimensions of concatenated tensors

### **Squeeze Operation**

***torch.squeeze(input: Tensor,dim: optional) -> Tensor***

args:

- input (Tensor): the input vector

- dim (int or tuple of ints,optional): if given the input will be squeezed only in specified dimensions

Returns a tensor with all specified dimensions of input of size 1 removed

**NOTE:** 
- The returned tensor shares the storage with the input tensor, so changing contents of one will change contents of another

- If tensor has a dimension of size 1 , the squeeze(input) will remove the dimension leading to unexpected errors




In [ ]:
# torch.squeeze()-  removes all single dimensions from a target tensor

print(f"Previous tensor:{x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed=x_reshaped.squeeze()
print(F"New tensor:{x_squeezed}")
print(f"New shape: {x_reshaped.squeeze().shape}")



Previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


### **Unsqueeze Operation**

***torch.unsqueeze(input,dim) -> Tensor***

args:

- input(Tensor): the input tensor

- dim(int) : the index at which to insert a singleton dimension

Returns a new tensor with a dimension of size one inserted at a specific position


In [ ]:
# torch.unsqueeze()- adds a single dimension to a target tensor at a specific dim(dimensio)

print(f"Previous target:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"New tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")


Previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])
New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape:torch.Size([1, 9])


In [ ]:
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
print(f"New tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")

New tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape:torch.Size([9, 1])


### **Permute Operation**

***torch.permute(input,dims) -> Tensor***

args:

    input(Tensor): the input tensor
    dims(tuple of int): the desired ordering of dimensions

Returns a view of the original tensor input with its dimensions permuted


In [ ]:
# torch.premute- rearranges the dimensions of a tensor in a specified order
x_original=torch.rand(size=(224,224,3)) #(height, width, color_channels)

x_permuted=x_original.permute(2,0,1) # (colour_channels,height,width) 
# shifts axis 0->1, 1->2, 2->0

print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")



Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])
