## Indexing in Tensors

Indexing with Pytorch is similar to indexing with NumPy


In [21]:
import torch

x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [22]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
# Indexing on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [24]:
x[0,0] 

tensor([1, 2, 3])

In [25]:
# Indexing on the most inner bracket
x[0][0][0]

tensor(1)

In [26]:
x[0][1][1]

tensor(5)

In [27]:
x[1][5][5]

IndexError: index 1 is out of bounds for dimension 0 with size 1

This is an error because the dimensions are [1,3,3] so we can index only upto [0,2,2]

In [ ]:
# Selecting all of a target dimension

x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimension but only index 1 of the 2nd dimension

x[:,:,1]


tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 or 0th and 1st dimension but all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## Pytorch and Numpy
Numpy is a popular library for scientific python numerical computing library

Therefore , PyTorch has functionality to interact with it

* Data in Numpy-> PyTorch tensor: torch.from_numpy(ndarray)
* PyTorch tensor-> Numpy: torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

Note that if we are going from numpy array to tensor then the default datatype is float64 as numpys default datatype is float64

In [ ]:
# Changing dtype of the tensor
tensor=torch.from_numpy(array).type(torch.float32)

In [ ]:
tensor.dtype

torch.float32

In [ ]:
# Change the value of an array
array+=1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

When we u use from_numpy function, the changes made to array are not reflected in the tensor

In [ ]:
# Tensor to Numpy array

tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Default datatype of torch is float32 so when we use .numpy that is reflected

In [28]:
# Change the tensor what happens to numpy array
tensor+=1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))