## Reproduciblity 

Trying to take the random out of random.

In short how a nueral network learns:
'start with random numbers->tensor operations->update random numbers to try to make them better representations of the data->repeat'

To reduce the randomness in NN, we have a concept called random seed



In [1]:
import torch

random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.4306, 0.3497, 0.3713, 0.9398],
        [0.1391, 0.4496, 0.9898, 0.8410],
        [0.9162, 0.9179, 0.5398, 0.1748]])
tensor([[0.1832, 0.2325, 0.0823, 0.9920],
        [0.8443, 0.2811, 0.0960, 0.7380],
        [0.8344, 0.3454, 0.4430, 0.9064]])


In [ ]:
print(random_tensor_A==random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# reproducible tensors
random_seed=42
torch.manual_seed(random_seed) # works only for one block of code
random_tensor_C=torch.rand(3,4)

torch.manual_seed(random_seed) #have to assign seed again to get same tensor
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [6]:
print(random_tensor_C==random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
