## Reproduciblity 

Trying to take the random out of random.

In short how a nueral network learns:
'start with random numbers->tensor operations->update random numbers to try to make them better representations of the data->repeat'

To reduce the randomness in NN, we have a concept called random seed



In [1]:
import torch

random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)

tensor([[0.6776, 0.7048, 0.8185, 0.6522],
        [0.2826, 0.0939, 0.7920, 0.8389],
        [0.1636, 0.2900, 0.5662, 0.5830]])
tensor([[0.3573, 0.0860, 0.9531, 0.3478],
        [0.2310, 0.5225, 0.7085, 0.4144],
        [0.8232, 1.0000, 0.9731, 0.1842]])


In [2]:
print(random_tensor_A==random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [3]:
# reproducible tensors
random_seed=42
torch.manual_seed(random_seed) # works only for one block of code
random_tensor_C=torch.rand(3,4)

torch.manual_seed(random_seed) #have to assign seed again to get same tensor
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [4]:
print(random_tensor_C==random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
